name: Deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.4
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20.18
          cache: 'pnpm'
      
      - name: Install dependencies
        working-directory: .
        run: pnpm install
      
      - name: Build
        working-directory: .
        run: pnpm docs:build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
          enable_jekyll: false
          keep_files: false
          commit_message: "deploy: update documentation site"
          exclude_assets: ''  # 不包含任何额外资产