name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/deploy.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
    paths-ignore:
      - 'README.md'
      - '*.md'
      - '!docs/**/*.md'  # 不忽略 docs 目录下的 md 文件

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 跳过重复的工作流
    concurrency:
      group: pages
      cancel-in-progress: false
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.4
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20.18
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run docs:build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          force_orphan: true
          enable_jekyll: false
          keep_files: false
          commit_message: "deploy: update documentation"
          # 确保只发布 VitePress 构建的内容
          force_orphan: true
          # 如果你想要部署到自定义域名，取消下面这行的注释并修改域名
          # cname: example.com